services:
  dev_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
